spring.application.name=ecommerce

# =========================
# DATABASE
# =========================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ecommerce_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# =========================
# JWT
# =========================
jwt.secret=${JWT_SECRET:CHANGE_THIS_TO_LONG_RANDOM_SECRET_64_CHARS_MINIMUM_CHANGE_ME_NOW_123456}
jwt.expiration=${JWT_EXPIRATION:86400000}

# =========================
# SWAGGER
# =========================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# =========================
# SERVER
# =========================
server.port=8080

# =========================
# JSON
# =========================
spring.jackson.default-property-inclusion=non_null